### ISSUE TITLE
Comparison with cateline.js

### ISSUE THREAD

**Issue by sashasochka** [keithwhor/multithread.js#2]
Hi, how does this library compare to https://github.com/calvinmetcalf/catiline ?

**Comment by keithwhor** [comment]
From a cursory overview of catiline:

1) multithread.js does not use promises. It expects a callback to be returned / triggered immediately upon execution of the worker thread.
2) multithread.js allows you to specify the number of maximum concurrent threads you'd like to use, and otherwise uses queueing (faster and more effective than trying to spawn too many different threads).
3) multithread.js supports special datatypes (processInt32, processFloat64) that perform significantly faster than sending JSON-serializable objects.

Three main differences that I can discern, though I haven't delved significantly into the catiline codebase.
